name: toshl-diff
version: '0.1.0.0'
license: Apache-2.0
author: Alexey Lebedeff
maintainer: binarin@binarin.ru
# cabal-version: ">=1.24"

default-extensions:
  - OverloadedStrings

custom-setup:
  dependencies: base, Cabal, cabal-doctest

dependencies:
- Decimal
- base >=4.9 && <4.10
- bytestring
- cassava
- containers
- data-default
- directory
- doctest
- extra
- file-embed
- filepath
- hspec
- hspec-expectations-pretty-diff
- lens
- raw-strings-qq
- safe
- stm
- text
- text-icu
- threepenny-gui >=0.8.0.0
- time
- vector

_exe-ghc-options: &exe-ghc-options
- -threaded
- -rtsopts
- -with-rtsopts=-N

library:
  source-dirs: src

executables:
  toshl-diff:
    main: Main.hs
    source-dirs: app
    ghc-options: *exe-ghc-options
    dependencies:
      - toshl-diff

tests:
  tests:
    main: Spec.hs
    source-dirs: tests
    ghc-options: *exe-ghc-options
    dependencies:
      - toshl-diff
  doctests:
    main: doctests.hs
    source-dirs: tests
    ghc-options: *exe-ghc-options
    dependencies:
      - toshl-diff
